/*
 * GovRegistry - Registries manager for GovHub
 *
 * Copyright (c) 2021-2023 Link.it srl (http://www.link.it).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.2.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.govhub.govregistry.readops.api.spec;

import java.util.List;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.springframework.data.domain.Sort.Direction;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import it.govhub.govregistry.commons.api.beans.Organization;
import it.govhub.govregistry.commons.api.beans.OrganizationList;
import it.govhub.govregistry.commons.api.beans.OrganizationOrdering;
import it.govhub.govregistry.commons.api.beans.Problem;

@Generated(value = "it.govhub.openapi.codegen.GovhubCodegenGenerator", date = "2023-03-30T13:10:58.167825+02:00[Europe/Rome]")
@Validated
@Tag(name = "Organization", description = "the Organization API")
@RequestMapping("/v1")
public interface OrganizationApi {

    /**
     * GET /organizations/{id}/logo : Retrieve the organization logo.
     * Retrieve the logo of the organization with the provided id.
     *
     * @param id  (required)
     * @return Successful operation. (status code 200)
     *         or Bad Request. (status code 400)
     *         or Required credentials missing. (status code 401)
     *         or Agent not authorized for the operation. (status code 403)
     *         or Not Found. (status code 404)
     *         or Too many requests. (status code 429)
     *         or Service Unavailable. (status code 503)
     *         or Unexpected error. (status code 200)
     */
    @Operation(
        operationId = "downloadOrganizationLogo",
        summary = "Retrieve the organization logo.",
        tags = { "organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "401", description = "Required credentials missing.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "403", description = "Agent not authorized for the operation.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "429", description = "Too many requests.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "200", description = "Unexpected error.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/organizations/{id}/logo",
        produces = { "application/octet-stream", "application/problem+json" }
    )
    ResponseEntity<org.springframework.core.io.Resource> downloadOrganizationLogo(
        @Min(0L) @Max(9223372036854775807L) @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    );


    /**
     * GET /organizations/{id}/logo-miniature : Retrieve the organization logo miniature
     * Retrieve the logo miniature of the organization with the provided id.
     *
     * @param id  (required)
     * @return Successful operation. (status code 200)
     *         or Bad Request. (status code 400)
     *         or Required credentials missing. (status code 401)
     *         or Agent not authorized for the operation. (status code 403)
     *         or Not Found. (status code 404)
     *         or Too many requests. (status code 429)
     *         or Service Unavailable. (status code 503)
     *         or Unexpected error. (status code 200)
     */
    @Operation(
        operationId = "downloadOrganizationLogoMiniature",
        summary = "Retrieve the organization logo miniature",
        tags = { "organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = org.springframework.core.io.Resource.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "401", description = "Required credentials missing.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "403", description = "Agent not authorized for the operation.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "429", description = "Too many requests.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "200", description = "Unexpected error.", content = {
                @Content(mediaType = "application/octet-stream", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/organizations/{id}/logo-miniature",
        produces = { "application/octet-stream", "application/problem+json" }
    )
    ResponseEntity<org.springframework.core.io.Resource> downloadOrganizationLogoMiniature(
        @Min(0L) @Max(9223372036854775807L) @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    );


    /**
     * GET /organizations : Retrieve the organization list.
     * Retrieve the organization list.
     *
     * @param sort Sorting field. (required)
     * @param sortDirection Direction Sorting field. (required)
     * @param limit Max number of provided items. (optional)
     * @param offset offset (zero-based) of indexed results. (optional, default to 0)
     * @param q generic query. (optional)
     * @param withRoles Retrieve the items for whose the principal has the roles. (optional)
     * @return Successful operation. (status code 200)
     *         or Bad Request. (status code 400)
     *         or Required credentials missing. (status code 401)
     *         or Agent not authorized for the operation. (status code 403)
     *         or Too many requests. (status code 429)
     *         or Service Unavailable. (status code 503)
     *         or Unexpected error. (status code 200)
     */
    @Operation(
        operationId = "listOrganizations",
        summary = "Retrieve the organization list.",
        tags = { "organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = OrganizationList.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = OrganizationList.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "401", description = "Required credentials missing.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "403", description = "Agent not authorized for the operation.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "429", description = "Too many requests.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "200", description = "Unexpected error.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/organizations",
        produces = { "application/hal+json", "application/problem+json" }
    )
    ResponseEntity<OrganizationList> listOrganizations(
        @NotNull @Parameter(name = "sort", description = "Sorting field.", required = true) @Valid @RequestParam(value = "sort", required = true, defaultValue = "id") OrganizationOrdering sort,
        @NotNull @Parameter(name = "sort_direction", description = "Direction Sorting field.", required = true) @Valid @RequestParam(value = "sort_direction", required = true, defaultValue = "desc") Direction sortDirection,
        @Min(1) @Max(100) @Parameter(name = "limit", description = "Max number of provided items.") @Valid @RequestParam(value = "limit", required = false) Integer limit,
        @Min(0L) @Max(9223372036854775807L) @Parameter(name = "offset", description = "offset (zero-based) of indexed results.") @Valid @RequestParam(value = "offset", required = false, defaultValue = "0") Long offset,
        @Pattern(regexp = "^[^\\u0000]*$") @Size(max = 255) @Parameter(name = "q", description = "generic query.") @Valid @RequestParam(value = "q", required = false) String q,
        @Parameter(name = "with_roles", description = "Retrieve the items for whose the principal has the roles.") @Valid @RequestParam(value = "with_roles", required = false) List<String> withRoles
    );


    /**
     * GET /organizations/{id} : Retrieve an Organization.
     * Retrieve the Organization with the provided id.
     *
     * @param id  (required)
     * @return Successful operation. (status code 200)
     *         or Bad Request. (status code 400)
     *         or Required credentials missing. (status code 401)
     *         or Agent not authorized for the operation. (status code 403)
     *         or Not Found. (status code 404)
     *         or Too many requests. (status code 429)
     *         or Service Unavailable. (status code 503)
     *         or Unexpected error. (status code 200)
     */
    @Operation(
        operationId = "readOrganization",
        summary = "Retrieve an Organization.",
        tags = { "organization" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful operation.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Organization.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Organization.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "401", description = "Required credentials missing.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "403", description = "Agent not authorized for the operation.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "429", description = "Too many requests.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "503", description = "Service Unavailable.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            }),
            @ApiResponse(responseCode = "200", description = "Unexpected error.", content = {
                @Content(mediaType = "application/hal+json", schema = @Schema(implementation = Problem.class)),
                @Content(mediaType = "application/problem+json", schema = @Schema(implementation = Problem.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/organizations/{id}",
        produces = { "application/hal+json", "application/problem+json" }
    )
    ResponseEntity<Organization> readOrganization(
        @Min(0L) @Max(9223372036854775807L) @Parameter(name = "id", description = "", required = true) @PathVariable("id") Long id
    );

}
