stages:
    - test
    - sonarqube
#    - build
#    - integration



variables: 
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    SONAR_HOST_URL: "http://localsonarqube:9000/"
    SONAR_TOKEN: "squ_35c667f3567119d5702ffa5fb92ca6eaac5889a6"
    SONAR_USER: "gitlab-runner"
    SONAR_PASSWORD: "Password@123"
default:
    cache:
        paths:
            - .m2/repository/
            - target/
    image: maven:3-openjdk-11

test:
    stage: test
    script:
        - mvn clean test
    artifacts:
        untracked: false
        name: test_and_coverage_report
        reports:
          junit: [ api/target/surefire-reports/*.xml ]
        expire_in: "1 week"

sonarqube:
    stage: sonarqube
    script:
        - mvn sonar:sonar
