stages:
  #- test
    - build
    - deploy

variables: 
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    SONAR_HOST_URL: "http://localsonarqube:9000/"
    SONAR_TOKEN: "squ_35c667f3567119d5702ffa5fb92ca6eaac5889a6"
    SONAR_USER: "gitlab-runner"
    SONAR_PASSWORD: "Password@123"
default:
    cache:
        paths:
            - .m2/repository/
            - target/
    image: maven:3-openjdk-11

build_java:
    stage: build
    script:
      - mvn verify -Pwar -DskipTests=true 
    artifacts:
        paths:
          - api/target/*.war
          - src/main/resources/*.sql
    only:
      - master
      - pipeline-test

build_angular:
    stage: build
    image: node:14.21.2-alpine3.16
    script:
      - cd webapp
      - npm install -g @angular/cli@v14-lts
      - npm install
      - npm run production-govregistry
      - cd dist
      - zip -r govregistry-app.zip .
    artifacts:
        paths:
          - webapp/dist/govregistry-app.zip
    only:
      - master
      - pipeline-test


