stages:
    - test
#    - sonarqube
#    - build
#    - integration



variables: 
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    SONAR_HOST_URL: "http://localsonarqube:9000/"
    SONAR_TOKEN: "squ_35c667f3567119d5702ffa5fb92ca6eaac5889a6"
    SONAR_USER: "gitlab-runner"
    SONAR_PASSWORD: "Password@123"
default:
    cache:
        paths:
            - .m2/repository/
            - target/
    image: maven:3-openjdk-11

test_and_coverage:
    stage: test
    script:
        - mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.coverage.jacoco.xmlReportPaths=report/target/site/jacoco-aggregate/jacoco.xml
    artifacts:
        untracked: false
        name: test_and_coverage_report
        reports:
          coverage_report:
            coverage_format: cobertura
            path: report/target/site/jacoco-aggregate/jacoco.xml
          junit: [ api/target/surefire-reports/*.xml, commons/target/surefire-reports/*.xml ]
        expire_in: "1 week"

