stages:
    - test
    - build_and_deploy
#    - integration



variables: 
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
    SONAR_HOST_URL: "http://localsonarqube:9000/"
    SONAR_TOKEN: "squ_35c667f3567119d5702ffa5fb92ca6eaac5889a6"
    SONAR_USER: "gitlab-runner"
    SONAR_PASSWORD: "Password@123"
default:
    cache:
        paths:
            - .m2/repository/
            - target/
    image: maven:3-openjdk-11

test:
    stage: test
    script:
      - mvn verify sonar:sonar
    artifacts:
        untracked: false
        name: test_and_coverage_report
        reports:
          junit: [ api/target/surefire-reports/*.xml ]
        expire_in: "1 week"

build_and_deploy:
    stage: build_and_deploy 
    script:
      - mvn verify -Pwar -DskipTests=true 
      - cp api/target/govregistry.war /opt/wildfly/govhub/deployments/
      - cd webapp
      - npm install
      - npm run production-govregistry
      - cp -r dist/govregistry-app /opt/wildfly/welcome-content/
