openapi: 3.0.3

info:
  title: GovHub Management Backoffice - OpenAPI 3.0
  x-summary: Backoffice GovHub
  description: This Service runs the shared govhub backoffice.
  x-api-id: management-govhub
  termsOfService: TODO
  version: 1.0.1

  contact:
    name: TODO
    email: TODO@TODO.it

  license:
    name: Apache 2.0 ( TODO )
    url: http://www.apache.org/licenses/LICENSE-2.0.html 

servers:
  - url: https://govhub.backoffice.it/api/v3
    description: Sample Deployment URL (Not Actual)

security:
   - header-principal: []

tags:
  - name: user
    description: Operations on users

paths:
  /users:
    post:
      tags:
        - user
      summary: Add a new user
      description: Add a new user
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '403':
          $ref: "#/components/responses/403Forbidden"
        '429':
          $ref: "#/components/responses/429TooManyRequests"
        '503':
          $ref: "#/components/responses/503ServiceUnavailable"
        default:
          $ref: "#/components/responses/ResponseDefault"

  /status:
    get:
      tags:
        - user
      summary: Get the system status
      description: Get the system status
      operationId: status
      responses:
        '200':
          description: Successful operation
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'          
        '400':
          $ref: "#/components/responses/400BadRequest"
        '401':
          $ref: "#/components/responses/401Unauthorized"
        '403':
          $ref: "#/components/responses/403Forbidden"
        '429':
          $ref: "#/components/responses/429TooManyRequests"
        '503':
          $ref: "#/components/responses/503ServiceUnavailable"
        default:
          $ref: "#/components/responses/ResponseDefault"

  
components:

   # SECURITY    ---------------
   securitySchemes:
      header-principal:
         type: apiKey
         in: header
         name: X-GovHub-Username

   # RESPONSES ---------------
   
   responses:
      '201Created':
         description: Resource created
         headers:
           Location:
             $ref: "#/components/headers/Location"
           Cache-Control:
              $ref: "#/components/headers/Cache-Control"
           X-RateLimit-Limit:
              $ref: "#/components/headers/X-RateLimit-Limit"
           X-RateLimit-Remaining:
              $ref: "#/components/headers/X-RateLimit-Remaining"
           X-RateLimit-Reset:
             $ref: "#/components/headers/X-RateLimit-Reset"

      '400BadRequest':
         description: Bad Request
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      '401Unauthorized':
         description: Required credentials missing
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      '403Forbidden':
         description: No Authorizations for the requested operation
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      '404NotFound':
         description: "Not Found"
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      '409Conflict':
         description: Conflict (The entity already exists)
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      '429TooManyRequests':
         description: Too many requests
         headers:
           Retry-After:
             $ref: "#/components/headers/Retry-After"
           X-RateLimit-Limit:
             $ref: "#/components/headers/X-RateLimit-Limit"
           X-RateLimit-Remaining:
             $ref: "#/components/headers/X-RateLimit-Remaining"
           X-RateLimit-Reset:
             $ref: "#/components/headers/X-RateLimit-Reset"
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      '503ServiceUnavailable':
         description: Service Unavailable
         headers:
           Retry-After:
             $ref: "#/components/headers/Retry-After"
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
      'ResponseDefault':
         description: Unexpected error
         content:
           application/problem+json:
             schema:
               $ref: "#/components/schemas/Problem"
            
    
   # HEADERS ---------------- #
   
                   
   headers:
      Location:
         description: >
             Header Location inserted in a response for a succesful POST request (201)
             The value is a link that points to the created object.
         schema:
           type: string
           format: url
           maxLength: 255
      Cache-Control:
        description: Management of objects cache, no-cache is the only supported option
        schema:          
          type: string
          pattern: ^[\w, -=]+$
          maxLength: 255
      Retry-After:
         description: Retry after a window of n seconds. See https://tools.ietf.org/html/rfc7231#section-7.1.3"
         schema:
           type: integer
           format: int32
           minimum: 0
           maximum: 2147483647
      X-RateLimit-Limit:
         description: Maximum number of allowed requests in the current time window
         schema:
           type: integer
           format: int32
           minimum: 0
           maximum: 2147483647
      X-RateLimit-Remaining:
         description: Number of remaining requests in the current time window
         schema:
           type: integer
           format: int32
           minimum: 0
           maximum: 2147483647
      X-RateLimit-Reset:
         description: Seconds left until the next time window.
         schema:
           type: integer
           format: int32
           minimum: 0
           maximum: 2147483647
           
           
   # SCHEMAS ---------------- #
   
   
   schemas:
      UserCreate:
         $ref: "#/components/schemas/User"
      User:
         type: object
         additionalProperties: false
         properties:
            principal:
               type: string
               maxLength: 255
               pattern: ^[\w _\-\.]+$
            full_name:
               type: string
               maxLength: 255               
               pattern: ^.*$
            email:
               type: string
               format: email
               maxLength: 255
            enabled:
               type: boolean
         required:
            - principal
            - name
            - email
            - enabled
      Problem:
         type: object
         additionalProperties: false
         properties:
           detail:
             type: string
             description: A human readable description of the occurred problem.
             example: Connection to database timed out
             maxLength: 255
             pattern: ^[ -~]+$
           instance:
             type: string
             description: Link to a specific occurence of the problem.
             format: uri
             maxLength: 255
           status:
             maximum: 600
             exclusiveMaximum: true
             minimum: 100
             type: integer
             description: HTTP Status Code.
             format: int32
             example: 503
           title:
             type: string
             description: Short description of the occurred problem.
             maxLength: 255
             pattern: ^[ -~]+$        
           type:
             type: string
             description: Absolute URI for the problem description.
             maxLength: 255
             format: uri
             example: "https://tools.ietf.org/html/rfc7231#section-6.6.4"
             default: about:blank
         