
-- PATCH 08-03-2020 - Renaming foreign key govregistry

alter table govhub_roles rename constraint govhub_roles_id_govhub_application_fkey TO GovhubRole_GovhubApplication;

alter table govhub_assignable_roles rename constraint govhub_assignable_roles_role_id_fkey TO GovhubAssRole_GovhubRole;
alter table govhub_assignable_roles rename constraint govhub_assignable_roles_assignable_role_id_fkey TO GovhubAssRole_AssignedGovhubRole;

alter table govhub_authorizations rename constraint govhub_authorizations_id_govhub_role_fkey TO GovhubAuth_GovhubRole;
alter table govhub_authorizations rename constraint govhub_authorizations_id_govhub_user_fkey TO GovhubAuth_GovhubUser;


alter table govhub_auth_organizations rename constraint govhub_auth_organizations_id_govhub_authorization_fkey TO GovhubAuthOrganization_GovhubAuth;
alter table govhub_auth_organizations rename constraint govhub_auth_organizations_id_govhub_organization_fkey TO GovhubAuthOrganization_GovhubOrganization;

alter table govhub_auth_services rename constraint govhub_auth_services_id_govhub_authorization_fkey TO GovhubAuthService_GovhubAuth;
alter table govhub_auth_services rename constraint govhub_auth_services_id_govhub_service_fkey TO GovhubAuthService_GovhubService;


-- PATCH 08-03-2020 

alter table govhub_services alter column name set not null;

